Repository insightsengineering/teal.code, pull requests merged in 2023-12, with the labels that each got.

#182 180 missing method `within.qenv.error`
  NAMESPACE
  NEWS.md
  R/qenv-within.R
  tests/testthat/test-qenv-within.R
Labels: core

#174 refactor branch for teal.code
  NEWS.md
  R/qenv-constructor.R
  R/qenv-eval_code.R
  R/qenv-get_code.R
  R/qenv-get_warnings.R
  R/qenv-replace_code.R
  R/utils.R
  README.md
  tests/testthat/test-qenv-replace_code.R
  tests/testthat/test-qenv-within.R
  tests/testthat/test-qenv_get_code.R
  tests/testthat/test-utils.R
  vignettes/qenv.Rmd
Labels: core, refactor

#186 94 `get_var` `inherits = FALSE`
  R/qenv-get_var.R
  tests/testthat/test-qenv_get_var.R
Labels: core

#163 remove `replace_code` function
  DESCRIPTION
  R/qenv-replace_code.R
  man/replace_code.Rd
  tests/testthat/test-qenv-replace_code.R
Labels: core

#185 collate seealso fields
  R/qenv-constructor.R
  R/qenv-within.R
  man/qenv.Rd
Labels: documentation, core

#183 165 trim trace for qenv.error@main
  R/qenv-get_code.R
  tests/testthat/test-qenv_get_code.R
Labels: core

#187 175 ls(qenv)
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/qenv-constructor.R
  R/qenv-get_env.R
  README.md
  _pkgdown.yml
  man/get_env.Rd
  man/qenv.Rd
  vignettes/qenv.Rmd
Labels: core
